# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ultra96v2_design/ultra96v2_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design || ORIG_REF_NAME==ultra96v2_design} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_zynq_ultra_ps_e_0_0/ultra96v2_design_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96v2_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_clk_wiz_0_0/ultra96v2_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_clk_wiz_0_0 || ORIG_REF_NAME==ultra96v2_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_0_0/ultra96v2_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_proc_sys_reset_0_0 || ORIG_REF_NAME==ultra96v2_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_proc_sys_reset_1_0 || ORIG_REF_NAME==ultra96v2_design_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_2_0/ultra96v2_design_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_proc_sys_reset_2_0 || ORIG_REF_NAME==ultra96v2_design_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_3_0/ultra96v2_design_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_proc_sys_reset_3_0 || ORIG_REF_NAME==ultra96v2_design_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_axi_intc_0_0/ultra96v2_design_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_axi_intc_0_0 || ORIG_REF_NAME==ultra96v2_design_axi_intc_0_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_ps8_0_axi_periph_0/ultra96v2_design_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_ps8_0_axi_periph_0 || ORIG_REF_NAME==ultra96v2_design_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ultra96v2_design/ip/ultra96v2_design_auto_pc_0/ultra96v2_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_design_auto_pc_0 || ORIG_REF_NAME==ultra96v2_design_auto_pc_0} -quiet] -quiet

# XDC: bd/ultra96v2_design/ultra96v2_design_ooc.xdc
