# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0.xci
# IP: The module: 'ultra96v2_design_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_design_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_design_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_design_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0.xci
# IP: The module: 'ultra96v2_design_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_design_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_design_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chtsao/aha/FPGA_gen_v2/ultra96v2-vitis-pkg/vivado/ultra96v2-xsa/ultra96v2-xsa.srcs/sources_1/bd/ultra96v2_design/ip/ultra96v2_design_proc_sys_reset_1_0/ultra96v2_design_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_design_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
